version: '2'
services:
  motowebui:
    build: .
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY_BASE=change_value_of_this_key_as_soon_as_you_realize_its_here_and_doesnt_look_safe
      - RAILS_SERVE_STATIC_FILES=1
    depends_on:
      - motowebui_db
  motowebui_db:
    image: mysql:5.7.16
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=motowebui