version: '2.1'
services:
  motowebui:
    build: .
    ports:
      - "${MWUI_PUBLIC_PORT:-3000}:3000"
    environment:
      - SECRET_KEY_BASE=change_value_of_this_key_as_soon_as_you_realize_its_here_and_doesnt_look_safe
      - RAILS_SERVE_STATIC_FILES=1
      - RAILS_ENV=production
      - MWUI_DB_NAME=motowebui
      - MWUI_DB_HOST=motowebui_db
      - MWUI_DB_USERNAME=motowebui_user
      - MWUI_DB_PASSWORD=motowebui_password
      - MWUI_MAX_RUNS_IN_SUITE=0 # maximum amount of Test Runs in Test Suite, oldest will be deleted, 0 - no limit
    depends_on:
      - motowebui_db
  motowebui_db:
    image: mysql:5.7.16
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_USER=motowebui_user
      - MYSQL_PASSWORD=motowebui_password
      - MYSQL_ROOT_PASSWORD=motowebui_root_password
      - MYSQL_DATABASE=motowebui
