default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['MWUI_DB_USERNAME'] %>
  password: <%= ENV['MWUI_DB_PASSWORD'] %>
  port: 3306
  pool: 5
  host: <%= ENV['MWUI_DB_HOST'] %>
  database: <%= ENV['MWUI_DB_NAME'] %>

development:
  <<: *default
  host: docker.demo
  database: motowebui_db

test:
  <<: *default

production:
  <<: *default