default: &default
  adapter: mysql2
  encoding: utf8
  username: <%= ENV['MWUI_DB_USERNAME'] %>
  password: <%= ENV['MWUI_DB_PASSWORD'] %>
  port: <%= ENV['MWUI_DB_PORT'] || 3306 %>
  pool: <%= ENV['MWUI_DB_POOL'] || 5%>
  host: <%= ENV['MWUI_DB_HOST'] %>
  database: <%= ENV['MWUI_DB_NAME'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default