default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root_password
  port: 3306
  pool: 5


development:
  <<: *default
  host: docker.demo
  database: motowebui

test:
  <<: *default
  host: motowebui_db
  database: motowebui

production:
  <<: *default
  host: motowebui_db
  database: motowebui